module.exports = {
  rootDir: '.',
  testEnvironment: 'jsdom',
  preset: 'ts-jest',
  globals: { 'ts-jest': { tsConfig: 'tsconfig.json' } },
  moduleDirectories: ['node_modules'],
  moduleFileExtensions: ['js', 'json', 'ts'],
  moduleNameMapper: { '\\.(css|scss)$': '<rootDir>/__mocks__/styleMock.js' },
  transform: { '^.+\\.ts$': 'ts-jest' },
  testURL: 'http://localhost/',
  testMatch: ['<rootDir>/src/**/*.spec.ts'],
  collectCoverageFrom: ['<rootDir>/src/**/*.spec.ts'],
  coveragePathIgnorePatterns: [
    '/node_modules/',
    '/specs/',
    '/tests/',
    '/testing/',
    '/test-helpers/',
    '/__mocks__/',
  ],
  coverageReporters: ['lcov', 'text-summary'],
  restoreMocks: true,
  verbose: true,
};
