name: CD
on:
  push:
    branches: [main, deploy]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: npm run check
      - run: npm run deploy
        env:
          TOKEN: ${{ secrets.TOKEN }}
